apiVersion: v1
kind: PersistentVolume
metadata:
  name: downloads-pv
spec:
  capacity:
    storage: 400Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/silo/downloads
    server: 172.31.31.3

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: downloads-pvc
spec:
  storageClassName: ""
  volumeName: downloads-pv
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 300Gi
