apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: media
  name: media-pv
spec:
  storageClassName: ""
  capacity:
    storage: 60Ti
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
    - nconnect=16
  nfs:
    path: /mnt/silo/media
    server: 172.31.31.3

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: ""
  resources:
    requests:
      storage: 12Ti
