---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  labels:
    app: vaultwarden
    app.kubernetes.io/name: vaultwarden
  namespace: restricted
spec:
  replicas: 0
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      containers:
        - name: vaultwarden
          image: vaultwarden/server:latest
          env:
            - name: DOMAIN
              value: "https://bitwarden.bugaychuk.com"
            - name: WEBSOCKET_ENABLED
              value: "true"
            - name: SIGNUPS_ALLOWED
              value: "true"
          volumeMounts:
            - name: vaultwarden-vol
              mountPath: /data
          ports:
            - containerPort: 80
      volumes:
        - name: vaultwarden-vol
          persistentVolumeClaim:
            claimName: vaultwarden-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-pvc
  namespace: restricted
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  namespace: restricted
spec:
  selector:
    app: vaultwarden
  ports:
    - protocol: TCP
      port: 38081
      targetPort: 80
  type: ClusterIP
