apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: "1.9.0"
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - kind: CustomResourceDefinition
      name: instancemanagers.longhorn.io
      jsonPointers:
        - /spec/preserveUnknownFields
    - kind: CustomResourceDefinition
      name: nodes.longhorn.io
      jsonPointers:
        - /spec/preserveUnknownFields
    - kind: CustomResourceDefinition
      name: replicas.longhorn.io
      jsonPointers:
        - /spec/preserveUnknownFields
    - kind: CustomResourceDefinition
      name: settings.longhorn.io
      jsonPointers:
        - /spec/preserveUnknownFields
    - kind: CustomResourceDefinition
      name: volumes.longhorn.io
      jsonPointers:
        - /spec/preserveUnknownFields
