apiVersion: v1
kind: Service
metadata:
  name: romm-svc
  namespace: media
spec:
  clusterIP: 10.104.102.41
  clusterIPs:
    - 10.104.102.41
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: romm
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
