apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: media
  name: downloads-pvc
spec:
  storageClassName: ""
  volumeName: downloads-pv
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 300Gi
