---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-nextcloud
  namespace: cloud
  annotations:
    cnpg.io/skipWalArchiving: "enabled"
spec:
  description: "Nextcloud PSQL cluster"
  imageName: ghcr.io/cloudnative-pg/postgresql:17.4
  instances: 1
  startDelay: 300
  stopDelay: 300
  primaryUpdateStrategy: unsupervised

  bootstrap:
    initdb:
      database: nextcloud_database
      owner: nextcloud
      secret:
        name: cluster-nextcloud
    # Alternative bootstrap method: start from a backup
    #recovery:
    #  backup:
    #    name: cluster-nextcloud

  enableSuperuserAccess: true
  superuserSecret:
    name: cluster-nextcloud-superuser

  storage:
    #storageClass: longhorn
    size: 4Gi

  postgresql:
    parameters:
      archive_mode: "off"

  backup:
    barmanObjectStore:
      destinationPath: s3://databases/nextcloud
      endpointURL: https://gateway.storjshare.io
      s3Credentials:
        accessKeyId:
          name: backup-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: backup-creds
          key: ACCESS_SECRET_KEY
      #wal:
      #  compression: gzip
      #  encryption: AES256
      data:
        compression: gzip
        encryption: AES256
        immediateCheckpoint: false
        jobs: 2
    retentionPolicy: "60d"
#  resources:
#    requests:
#      memory: "512Mi"
#      cpu: "1"
#    limits:
#      memory: "1Gi"
#      cpu: "2"

#  affinity:
#    enablePodAntiAffinity: true
#    topologyKey: failure-domain.beta.kubernetes.io/zone

#  nodeMaintenanceWindow:
#    inProgress: false
#    reusePVC: false

