apiVersion: v1
kind: Pod
metadata:
  name: tmp
  namespace: cloud
spec:
  containers:
    - name: tmp
      image: instrumentisto/rsync-ssh
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - mountPath: "/nextcloud-data"
          name: nextcloud-data
        - mountPath: "/nextcloud-nextcloud"
          name: nextcloud-nextcloud
        - mountPath: "/nextcloud-db"
          name: nextcloud-db
  volumes:
    - name: nextcloud-data
      persistentVolumeClaim:
        claimName: nextcloud-aio-nextcloud-data
    - name: nextcloud-nextcloud
      persistentVolumeClaim:
        claimName: nextcloud-aio-nextcloud
    - name: nextcloud-db
      persistentVolumeClaim:
        claimName: nextcloud-aio-database
