apiVersion: v1
kind: Secret
metadata:
  name: cluster-nextcloud
  namespace: cloud
  annotations:
    avp.kubernetes.io/path: "/v1/homelab/data/nextcloud-db"
type: Opaque
stringData:
  username: "<nextcloud-user>"
  password: "<nextcloud-pass>"

---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-nextcloud-superuser
  namespace: cloud
  annotations:
    avp.kubernetes.io/path: "/v1/homelab/data/nextcloud-db"
type: Opaque
stringData:
  username: "<postgress-user>"
  password: "<postgress-pass>"

---
apiVersion: v1
kind: Secret
metadata:
  name: backup-creds
  namespace: cloud
  annotations:
    avp.kubernetes.io/path: "/v1/homelab/data/storj-db-s3bucket"
type: Opaque
stringData:
  ACCESS_KEY_ID: "<ACCESS_KEY_ID>"
  ACCESS_SECRET_KEY: "<ACCESS_SECRET_KEY>"
