apiVersion: v1
kind: Secret
metadata:
  name: cluster-nextcloud
  namespace: cloud
  annotations:
    avp.kubernetes.io/path: "/homelab/data/nextcloud-db"
    avp.kubernetes.io/kv-version: "2"
#type: Opaque
stringData:
  username: "<nextcloud-user>"
  password: "<nextcloud-pass>"

---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-nextcloud-superuser
  namespace: cloud
  annotations:
    avp.kubernetes.io/path: "/homelab/data/nextcloud-db"
    avp.kubernetes.io/kv-version: "2"
#type: Opaque
stringData:
  username: "<postgres-user>"
  password: "<postgres-pass>"

---
apiVersion: v1
kind: Secret
metadata:
  name: backup-creds
  namespace: cloud
  annotations:
    avp.kubernetes.io/path: "/homelab/data/storj-db-s3bucket"
    avp.kubernetes.io/kv-version: "2"
#type: Opaque
stringData:
  ACCESS_KEY_ID: "<ACCESS_KEY_ID>"
  ACCESS_SECRET_KEY: "<ACCESS_SECRET_KEY>"

---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secret
  namespace: cloud
  annotations:
    avp.kubernetes.io/path: "/homelab/data/nextcloud"
    avp.kubernetes.io/kv-version: "2"
#type: Opaque
stringData:
  admin-user: "<admin-user>"
  admin-password: "<admin-password>"
  redis-password: "<redis-password>"
