apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system

---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: metallb
  namespace: metallb-system
spec:
  repo: https://metallb.github.io/metallb
  chart: metallb
  targetNamespace: metallb-system

---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: kubelab-pool
  namespace: metallb-system
spec:
  addresses:
    - 172.31.31.5/32

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: homek3s-l2
  namespace: metallb-system
spec:
  ipAddressPools:
    - kubelab-pool
