---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: kubelab-pool
  namespace: metallb-system
spec:
  addresses:
    - 172.31.31.250-172.31.31.254

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: homek8s-l2
  namespace: metallb-system
spec:
  ipAddressPools:
    - kubelab-pool
