apiVersion: v1
kind: PersistentVolume
metadata:
  name: romm-lib-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 60Ti
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: romm-lib-pvc
    namespace: media
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /mnt/silo/data/games/library # path of the nfs share
    server: 172.31.31.3 # IP of the NFS server
  persistentVolumeReclaimPolicy: Retain # do not automatically delete data
  volumeMode: Filesystem
