apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyseer-ingress
  namespace: media
spec:
  ingressClassName: nginx
  rules:
    - host: "js.bugaychuk.com"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: jellyseer-svc
                port:
                  number: 5055
    - host: "js.home.arpa"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: jellyseer-svc
                port:
                  number: 5055
