apiVersion: v1
kind: Service
metadata:
  labels:
    app: bazarr
  name: bazarr-svc
  namespace: media
spec:
  ports:
    - port: 6767
      protocol: TCP
      targetPort: 6767
  selector:
    app: bazarr
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
