apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app":"jellyfin"},"name":"jellyfin-svc","namespace":"media"},"spec":{"ports":[{"name":"discover-jelly","port":7359,"protocol":"UDP","targetPort":7359},{"name":"discovery-dlna","port":1900,"protocol":"UDP","targetPort":1900},{"name":"https","port":8920,"protocol":"TCP","targetPort":8920},{"name":"http","port":8096,"protocol":"TCP","targetPort":8096}],"selector":{"app":"jellyfin"}}}
  labels:
    app: jellyfin
  name: jellyfin-svc
  namespace: media
spec:
  clusterIP: 10.102.21.103
  clusterIPs:
    - 10.102.21.103
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: discover-jelly
      port: 7359
      protocol: UDP
      targetPort: 7359
    - name: discovery-dlna
      port: 1900
      protocol: UDP
      targetPort: 1900
    - name: https
      port: 8920
      protocol: TCP
      targetPort: 8920
    - name: http
      port: 8096
      protocol: TCP
      targetPort: 8096
  selector:
    app: jellyfin
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
