apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paperless-ngx
  namespace: argocd
spec:
  backup:
    barmanObjectStore:
      data:
        compression: gzip
        encryption: AES256
        immediateCheckpoint: false
        jobs: 2
      destinationPath: s3://databases/paperless
      endpointURL: https://gateway.storjshare.io
      s3Credentials:
        accessKeyId:
          key: ACCESS_KEY_ID
          name: backup-creds
        secretAccessKey:
          key: ACCESS_SECRET_KEY
          name: backup-creds
    retentionPolicy: 60d
    target: prefer-standby
  destination:
    namespace: restricted
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/vityobug/homelab.git
    targetRevision: HEAD
    path: apps/paperless-ngx
  #syncPolicy:
  #  automated:
  #    prune: true
  #    selfHeal: true
  ignoreDifferences:
    - kind: Cluster
      group: postgresql.cnpg.io
      name: cluster-paperless
      namespace: restricted
      jsonPointers:
        - /metadata/generation
        - /metadata/resourceVersion
        - /metadata/annotations/kubectl.kubernetes.io/last-applied-configuration
        - /status
        - /spec/affinity
        - /spec/bootstrap
        - /spec/enablePDB
