apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-paperless
  namespace: restricted
spec:
  superuserSecret:
    name: cluster-paperless-superuser

  bootstrap:
    recovery:
      source: restore-src

  externalClusters:
    - name: restore-src
      barmanObjectStore:
        destinationPath: s3://databases/paperless/ # location with wals and base
        endpointURL: https://gateway.storjshare.io
        serverName: cluster-paperless
        s3Credentials:
          accessKeyId:
            name: backup-creds
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: backup-creds
            key: ACCESS_SECRET_KEY
        wal:
          maxParallel: 8

  storage:
    size: 2Gi
  instances: 1
  enableSuperuserAccess: true
