apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  annotations:
    cnpg.io/skipWalArchiving: enabled
  name: cluster-paperless
  namespace: restricted
spec:
  backup:
    barmanObjectStore:
      data:
        compression: gzip
        encryption: AES256
        immediateCheckpoint: false
        jobs: 2
      destinationPath: s3://databases/paperless
      endpointURL: https://gateway.storjshare.io
      s3Credentials:
        accessKeyId:
          key: ACCESS_KEY_ID
          name: backup-creds
        secretAccessKey:
          key: ACCESS_SECRET_KEY
          name: backup-creds
    retentionPolicy: 60d
    target: prefer-standby
  bootstrap:
    recovery:
      database: app
      owner: app
      source: restore-src
  enableSuperuserAccess: true
  externalClusters:
    - barmanObjectStore:
        destinationPath: s3://databases/paperless/
        endpointURL: https://gateway.storjshare.io
        s3Credentials:
          accessKeyId:
            key: ACCESS_KEY_ID
            name: backup-creds
          secretAccessKey:
            key: ACCESS_SECRET_KEY
            name: backup-creds
        serverName: paperless-ngx
      name: restore-src
  storage:
    size: 2Gi
  superuserSecret:
    name: paperless-ngx
