apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-paperless
  namespace: restricted
  resourceVersion: "6224305"
  annotations:
    cnpg.io/skipWalArchiving: enabled
spec:
  backup:
    barmanObjectStore:
      data:
        compression: gzip
        encryption: AES256
        immediateCheckpoint: false
        jobs: 2
      destinationPath: s3://databases/paperless
      endpointURL: https://gateway.storjshare.io
      s3Credentials:
        accessKeyId:
          key: ACCESS_KEY_ID
          name: backup-creds
        secretAccessKey:
          key: ACCESS_SECRET_KEY
          name: backup-creds
    retentionPolicy: 60d
    target: prefer-standby
  superuserSecret:
    name: cluster-paperless-superuser

  bootstrap:
    recovery:
      source: restore-src

  externalClusters:
    - name: restore-src
      barmanObjectStore:
        destinationPath: s3://databases/paperless/ # location with wals and base
        endpointURL: https://gateway.storjshare.io
        serverName: paperless-ngx
        s3Credentials:
          accessKeyId:
            name: backup-creds
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: backup-creds
            key: ACCESS_SECRET_KEY

  storage:
    resizeInUseVolumes: true
    size: 2Gi
  instances: 1
  enableSuperuserAccess: true
