---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-paperless
  namespace: restricted
spec:
  description: "Paperless PSQL cluster"
  imageName: ghcr.io/cloudnative-pg/postgresql:17.4
  # imagePullSecret is only required if the images are located in a private registry
  # imagePullSecrets:
  #   - name: private_registry_access
  instances: 1
  startDelay: 300
  stopDelay: 300
  primaryUpdateStrategy: unsupervised

  bootstrap:
    initdb:
      database: paperless
      owner: paperless
      secret:
        name: cluster-paperless-app-user
    # Alternative bootstrap method: start from a backup
    #recovery:
    #  backup:
    #    name: cluster-paperless

  enableSuperuserAccess: true
  superuserSecret:
    name: cluster-paperless-superuser

  storage:
    #storageClass: longhorn
    size: 2Gi

  backup:
    barmanObjectStore:
      destinationPath: s3://databases/paperless
      endpointURL: https://gateway.storjshare.io
      s3Credentials:
        accessKeyId:
          name: backup-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: backup-creds
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
        encryption: AES256
      data:
        compression: gzip
        encryption: AES256
        immediateCheckpoint: false
        jobs: 2
    retentionPolicy: "60d"
#  resources:
#    requests:
#      memory: "512Mi"
#      cpu: "1"
#    limits:
#      memory: "1Gi"
#      cpu: "2"

#  affinity:
#    enablePodAntiAffinity: true
#    topologyKey: failure-domain.beta.kubernetes.io/zone

#  nodeMaintenanceWindow:
#    inProgress: false
#    reusePVC: false

