apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-paperless-restore-test
  namespace: restricted
spec:
  instances: 1
  storage:
    size: 2Gi
  bootstrap:
    recovery:
      backup:
        name: paperless-backup
  enableSuperuserAccess: true
  superuserSecret:
    name: cluster-paperless-superuser
