---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-data
  namespace: restricted
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-export
  namespace: restricted
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
  storageClassName: longhorn

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: restricted
  name: paperless-consume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
  storageClassName: longhorn

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: restricted
  name: paperless-media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: restricted
  name: redis-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless
  labels:
    app: paperless
    app.kubernetes.io/name: paperless
  namespace: restricted
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paperless
  template:
    metadata:
      labels:
        app: paperless
      namespace: restricted
    spec:
      containers:
        - name: redis
          image: redis:7
          volumeMounts:
            - name: redis-data
              mountPath: /data
          #args: ["--appendonly", "yes"]

        - name: paperless-webserver
          image: ghcr.io/paperless-ngx/paperless-ngx:latest
          ports:
            - containerPort: 8000
          env:
            - name: PAPERLESS_REDIS
              value: redis://localhost:6379
            - name: PAPERLESS_OCR_LANGUAGES
              value: "eng rus bul"
            - name: PAPERLESS_OCR_LANGUAGE
              value: bul
            - name: PAPERLESS_TIME_ZONE
              value: "Europe/Sofia"
            - name: PAPERLESS_DBHOST
              value: cluster-paperless-rw.restricted.svc.cluster.local
            - name: PAPERLESS_DBUSER
              valueFrom:
                secretKeyRef:
                  name: cluster-paperless-app-user
                  key: username
            - name: PAPERLESS_DBPASS
              valueFrom:
                secretKeyRef:
                  name: cluster-paperless-app-user
                  key: password
            - name: PAPERLESS_DBNAME
              value: paperless
          volumeMounts:
            - name: paperless-data
              mountPath: /usr/src/paperless/data
            - name: paperless-media
              mountPath: /usr/src/paperless/media
            - name: export
              mountPath: /usr/src/paperless/export
            - name: consume
              mountPath: /usr/src/paperless/consume
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data
        - name: paperless-data
          persistentVolumeClaim:
            claimName: paperless-data
        - name: paperless-media
          persistentVolumeClaim:
            claimName: paperless-media
        - name: export
          persistentVolumeClaim:
            claimName: paperless-export
        - name: consume
          persistentVolumeClaim:
            claimName: paperless-consume

---
apiVersion: v1
kind: Service
metadata:
  name: paperless
  namespace: restricted
spec:
  type: ClusterIP
  selector:
    app: paperless
  ports:
    - name: http
      port: 8000
      targetPort: 8000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paperless
  namespace: restricted
spec:
  ingressClassName: nginx
  rules:
    - host: "docs.bugaychuk.com"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: paperless
                port:
                  number: 8000
