apiVersion: v1
kind: Secret
metadata:
  name: paperless-ngx
  namespace: restricted
  annotations:
    avp.kubernetes.io/path: "/homelab/data/paperless-ngx"
    avp.kubernetes.io/kv-version: "2"
stringData:
  username: "<username>"
  password: "<password>"
  superuser-db: "<superuser-db>"
  superpass-db: "<superpass-db>"

---
apiVersion: v1
kind: Secret
metadata:
  name: backup-creds
  namespace: restricted
  annotations:
    avp.kubernetes.io/path: "/homelab/data/storj-db-s3bucket"
    avp.kubernetes.io/kv-version: "2"
stringData:
  ACCESS_KEY_ID: "<ACCESS_KEY_ID>"
  ACCESS_SECRET_KEY: "<ACCESS_SECRET_KEY>"
