apiVersion: v1
data:
  password: cGFwZXJsZXNz
  username: cGFwZXJsZXNz
kind: Secret
metadata:
  name: cluster-paperless-app-user
  namespace: restricted
type: kubernetes.io/basic-auth

---
apiVersion: v1
data:
  password: cGFwZXJsZXNz
  username: cGFwZXJsZXNz
kind: Secret
metadata:
  name: cluster-paperless-superuser
  namespace: restricted
type: kubernetes.io/basic-auth

---
apiVersion: v1
kind: Secret
metadata:
  name: backup-creds
  namespace: restricted
data:
  ACCESS_KEY_ID: cGFwZXJsZXNz
  ACCESS_SECRET_KEY: cGFwZXJsZXNz
